### PR TITLE
Make docs actually enumerate the module classes

### PR DESCRIPTION
**Pull request by nsmith-**

### CODE REVIEW

**Comment by ScottDemarest** [comment]
It looks good to me but I have yet to approve because git hub doesn't seem to be running the checks properly. I tried merging this branch with main before approving, just in case, but now the checks have halted and I get an error when I try to look at the details.

**Comment by ScottDemarest** [comment]
I get error code 500. Looks like a server error. Should probably be resolved later. I'll approve it then.

**Review by ScottDemarest — APPROVED** [review]
Looks good

**Comment by nsmith-** [comment]
ahh it didn't work in the CI because https://github.com/CoffeaTeam/fsspec-xrootd/runs/8027640008?check_suite_focus=true#step:5:19

**Pull request merged**
