### PR TITLE
Make sure storage option actually survives

### PR DESCRIPTION
**Pull request by nsmith-**

### CODE REVIEW

**Comment by ScottDemarest** [comment]
It passes the tests but I don't think the problem is really fixed.

**Comment by nsmith-** [comment]
I suppose some change to whether a root path is `''` or `'/'` might mess with how the cache logic works?

**Comment by nsmith-** [comment]
Actually no, I take that back. The tests were failing even with the first commit

**Comment by ScottDemarest** [comment]
It works now! For some reason, moving test_pickle after test_read fixes everything

**Comment by ScottDemarest** [comment]
It turns out the _ls_from_cache() function returns an empty array if the requested path is in the cache but has no directories beneath it. I added a check for an empty array in _info() to accommodate this and now it passes all tests regardless of the order. I don't fully understand why the test order mattered before but I think it is fixed now.

**Review by ScottDemarest — APPROVED** [review]
Everything looks good now.

**Pull request merged**
